@startuml

start
:Khởi tạo các biến cần thiết;
:Tạo và mở cổng COM ảo có Baudrate 962500;
:Khởi tạo file .csv để lưu data;
:Bắt đầu đếm thời gian dùng hàm 'tic';

while (while(true))
    : Pause(0.01) \n Cập nhật thời gian hiện tại bằng hàm 'toc';
    if (s.BytesAvailable > 0) then (true)
        :Đọc 10 byte data vừa nhận được;
        if (byte_1 == 255 and byte_2 == 255) then (true)
            if (byte_3 == 0 and byte_4 == 0) then (true)
                :Thoát vòng lặp;
            else if (byte_3 == 1 and byte_4 == 1) then (true)
                :Bắt đầu Record data;
            else if (byte_3 == 2 and byte_4 == 2) then (true)
                :Dừng Record data;
            endif
        endif
        :Convert các giá trị từ 2 byte sang kiểu số thực cho các giá trị góc;
        :Cập nhật hình dạng của Robot trên Simulink;
        :Tính động học thuận tìm ra các giá trị vị trí px, py, pz;
        :Vẽ các đồ thị giá trị góc và tọa độ đầu tay gắp trong không gian;
    endif
endwhile (break)

: Close và Delete cổng COM đã khởi tạo;
: Đóng file .csv;

stop

@enduml
